[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "Web application of 'submitting papers' in ORSJ."
homepage = "https://github.com/SaitoTsutomu/orsj-submit"
license = "Apache-2.0"
name = "orsj-submit"
readme = "README.md"
version = "0.1.1"

[tool.poetry.scripts]
orsj-submit = "orsj_submit:main"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
flake8 = "^6.0.0"
flask = "^2.2.2"
gunicorn = "^20.1.0"
isort = "^5.10.1"
mypy = "^0.991"
pdfformfiller = "^0.4"
pyjade = "^4.0.0"
pypdf2 = "1.26.0"
pytest = "^7.2.0"
pyyaml = "^6.0"
redis = "^4.5.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
