[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "Web application of 'submitting papers' in ORSJ."
homepage = "https://github.com/SaitoTsutomu/orsj-submit"
license = "MIT"
name = "orsj-submit"
readme = "README.md"
version = "0.0.4"

[tool.poetry.scripts]
orsj-submit = "orsj_submit:main"

[tool.poetry.dependencies]
flask = "^1.1.2"
gunicorn = "^20.0.4"
pdfformfiller = "^0.4"
pyjade = "^4.0.0"
pypdf2 = "^1.26.0"
python = "^3.8"
pyyaml = "^5.3.1"
redis = "^3.4.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
isort = "^4.3.21"
mypy = "^0.770"
pytest = "^5.2"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
